### ISSUE TITLE
error occurs when using :bash install_torch_v1.9.sh 

### ISSUE THREAD

**Issue by fatfishlin** [NVIDIA-AI-IOT/scene-text-recognition#2]
hi,error occurs when I use :bash install_torch_v1.9.sh ,infor is :
/tmp/torchvision/torchvision/csrc/ops/autocast/deform_conv2d_kernel.cpp: In function ‘at::Tensor vision::ops::{anonymous}::deform_conv2d_autocast(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, bool)’:
/tmp/torchvision/torchvision/csrc/ops/autocast/deform_conv2d_kernel.cpp:28:28: error: ‘cached_cast’ is not a member of ‘at::autocast’
              at::autocast::cached_cast(at::kFloat, input),

please help me ,thanks

**Comment by gitwavelet** [comment]
I guess you should install requirements.txt first. 
(correct the typo to python-bidi==0.4.2 in requirements.txt) 

And you need to edit 'install_torch_v1.9.sh' to install PyTorch first. 
(last two lines) 
 install_torch
 \# install_torchvision

And then, install torchvision.
 \# install_torch
 install_torchvision

**Comment by fatfishlin** [comment]
when I run:
pip3 install -r requirements.txt
errs occur :
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-b7z9rpz2/opencv-python/

**Comment by gitwavelet** [comment]
You should check the pip version and upgrade it.

**Comment by husnejahan** [comment]
Hi 

I am getting error

**corrected the typo to python-bidi==0.4.2 in requirements.txt**

**edited  'install_torch_v1.9.sh' to install PyTorch first.
(last two lines)
install_torch
# install_torchvision

And then, install torchvision.
# install_torch
install_torchvision**

fatal: destination path '/tmp/torchvision' already exists and is not an empty directory.
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by husnejahan** [comment]
Hi 

I am getting error

**corrected the typo to python-bidi==0.4.2 in requirements.txt**

**edited  'install_torch_v1.9.sh' to install PyTorch first.
(last two lines)
install_torch
# install_torchvision

And then, install torchvision.
# install_torch
install_torchvision**

fatal: destination path '/tmp/torchvision' already exists and is not an empty directory.
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
